const GatewayCodesPt = {
    // 10000 - Códigos de erro
    'CH21': `O código identificador do banco especificado na mensagem está em formato incorreto
            O identificador do banco é inválido ou está ausente
            O código da agência é inválido ou está ausente
            Incompatibilidade entre o BIC do agente credor e o IBAN
            Ocorreu um erro em %FIELD_NAME_1%
            A transação não é única`,
    'RC02': `O código identificador do banco especificado na mensagem está em formato incorreto
            O identificador do banco é inválido ou está ausente
            O código da agência é inválido ou está ausente
            Incompatibilidade entre o BIC do agente credor e o IBAN
            Ocorreu um erro em %FIELD_NAME_1%
            A transação não é única`,
    'DT01': 'Ocorreu um erro em %FIELD_NAME_1%',
    'AM14': 'Ocorreu um erro em %FIELD_NAME_1%. O valor da transação excede os limites acordados entre o banco e o cliente.',
    'AM06': 'Ocorreu um erro em %FIELD_NAME_1%',
    'CH16': `A informação de remessa estruturada inclui caracteres alfanuméricos ou mais de 16 dígitos
            Ocorreu um erro em %FIELD_NAME_1%
            Código do país inválido
            QR Code expirado
            Status do QR Code inativo`,
    'BE15': 'Ocorreu um erro em %FIELD_NAME_1%. ID do proxy não ativo',
    'NARR': 'Ocorreu um erro em %FIELD_NAME_1%',
    // 11000 - Códigos de erro
    'AB01': 'Processo de compensação abortado devido a tempo esgotado',
    'AB02': 'Processo de compensação abortado devido a um erro fatal',
    'AB03': 'Liquidação abortada devido a tempo esgotado',
    'AB05': 'Transação parada devido a tempo esgotado no agente credor',
    'AB06': 'Transação parada devido a tempo esgotado no agente instruído',
    'AB07': 'Agente da mensagem não está online',
    'AB08': 'Agente credor não está online',
    'AB09': 'Transação parada devido a erro no agente credor',
    'AB10': 'Processo de compensação abortado devido a erro no PSP intermediário ou CSM (o agente instruído).',
    'AC04': 'Número da conta especificada foi encerrado nos livros do banco',
    'AC05': 'Número da conta do devedor encerrado',
    'AC06': 'Conta especificada está bloqueada, proibindo a postagem de transações contra ela',
    'AC07': 'Número da conta do credor encerrado',
    'AG01': 'Transação proibida neste tipo de conta (anteriormente Sem Acordo)',
    'AG02': 'Código da operação bancária especificado na mensagem não é válido para o destinatário',
    'AG03': 'Tipo de transação não suportado ou autorizado nesta conta',
    'AG07': 'Conta do devedor não pode ser debitada por um motivo genérico',
    'AG09': 'Pagamento original nunca recebido',
    'AG10': 'Agente da mensagem suspenso do sistema de pagamento em tempo real',
    'AG11': 'PSP do beneficiário da mensagem suspenso do sistema de pagamento em tempo real',
    'AG12': 'Validação de pré-autorização falhou',
    'AM03': 'O valor da mensagem especificada é uma moeda não processável fora do acordo existente',
    'AM04': 'Valor dos fundos disponíveis para cobrir o valor da mensagem especificada é insuficiente',
    'AM05': 'Duplicação',
    'AM20': 'Número de transações no nível de informação de pagamento é inválido',
    'ARDT': 'Já devolvido. Cancelamento não aceito pois a transação já foi devolvida.',
    'BE01': 'Identificação do cliente final não é consistente com o número da conta associada.',
    'BE06': 'Cliente final especificado não é conhecido no código do banco de triagem ou nacional ou não existe mais nos livros',
    'BE07': 'Especificação do endereço do devedor, que é necessária para pagamento, está ausente/incorreta',
    'BE10': 'Código do país do devedor está ausente ou inválido',
    'BE11': 'Código do país do credor está ausente ou inválido',
    'BE12': 'Código do país de residência está ausente ou inválido',
    'CH09': 'Alterações no mandato não são permitidas',
    'CH11': 'Valor no identificador do credor está incorreto',
    'CNOR': 'Banco credor não está registrado sob este BIC no CSM',
    'CUST': 'Cancelamento solicitado pelo devedor',
    'DNOR': 'Banco devedor não está registrado sob este BIC no CSM',
    'DS02': 'Pedido Cancelado',
    'DS04': 'Pedido Rejeitado',
    'DS09': 'A descriptografia do arquivo não foi bem-sucedida',
    'DS0B': 'Assinatura de dados para o formato não está disponível ou é inválida',
    'DS0D': 'Certificado de assinatura não válido',
    'DS0G': 'Assinante não está autorizado a assinar este tipo de operação.',
    'DS0H': 'Assinante não está autorizado a assinar para esta conta',
    'DS24': 'Tempo de espera expirado',
    'EC46': 'Rejeição por sanções',
    'ED05': 'Liquidação da transação falhou',
    'ED06': 'Sistema de liquidação interbancária não disponível',
    'FF01': 'Formato do arquivo incompleto ou inválido',
    'FF02': 'Erro de sintaxe, razão fornecida como informação narrativa nas informações adicionais de motivo',
    'FF03': 'Informação do tipo de pagamento está ausente ou inválida',
    'FF10': 'Arquivo ou transação não pode ser processado devido a problemas técnicos no lado do banco',
    'FF11': 'Pedido de compensação rejeitado por estar sujeito a uma operação de abortamento',
    'FOCR': 'Seguindo pedido de cancelamento',
    'FR01': 'Devolvido como resultado de fraude',
    'FRAD': 'Transação SCT Inst original fraudulenta',
    'FRAUD01': 'A conta do credor não é elegível para pagamentos em tempo real. Seu pagamento não pôde ser processado.',
    'FRTR': 'Resposta final - Repetir tentativa de não resposta anterior.',
    'IN06': 'O ABA do credor não é elegível para pagamentos em tempo real. Seu pagamento não pôde ser processado.',
    'IN12': 'O canal designado não é elegível para pagamentos em tempo real. Seu pagamento não pôde ser processado.',
    'IN14': 'O pagamento tem campos que excedem os limites de caracteres. Por favor, faça as correções necessárias e tente novamente.',
    'LEGL': 'Decisão Legal',
    'MD01': 'Sem Mandato',
    'MD02': 'Informações relacionadas ao mandato requeridas pelo esquema estão ausentes',
    'MD06': 'Devolução de fundos solicitada pelo cliente final',
    'MD07': 'Cliente final está falecido',
    'NOAS': 'Sem resposta do Beneficiário',
    'NOAT': 'Mensagem TCH - Conta do cliente destinatário não suporta/aceita este tipo de mensagem',
    'NOOR': 'Transação SCT Inst inicial nunca recebida',
    'PC04': 'Cartão perdido/roubado',
    'PC05': 'Rejeitado',
    'PC43': 'Cartão perdido/roubado',
    'PC57': 'Transação não permitida para o portador do cartão',
    'PC61': 'Excede limites de retirada',
    'PC62': 'Cartão restrito',
    'PC65': 'Limite de contagem de atividades excedido',
    'PR05': 'Proxy duplicado no banco',
    'PR06': 'Proxy duplicado em outro banco',
    'PR07': 'Proxy já registrado/transferido',
    'PR08': 'Proxy já desregistrado',
    'PR09': 'Proxy já suspenso',
    'PR10': 'Tempo limite da solicitação de proxy',
    'PR11': 'Outro motivo de rejeição do proxy',
    'RC09': 'Identificador do membro do sistema de compensação do devedor é inválido ou está ausente',
    'RC10': 'Identificador do membro do sistema de compensação do credor é inválido ou está ausente',
    'RF01': 'Referência da transação não é única dentro da mensagem',
    'RR04': 'Motivo regulatório',
    'RR05': 'Informações de relatório regulatório ou do banco central ausentes, incompletas ou inválidas',
    'RR10': 'Conjunto de caracteres fornecido não é válido para o país e tipo de pagamento.',
    'SL03': 'Devido a um serviço específico oferecido pelo sistema de compensação',
    'TA01': 'A transmissão do arquivo não foi bem-sucedida, teve que ser abortada (por motivos técnicos)',
    'TECH': 'Problema Técnico',
    'TK01': 'Token inválido',
    'TK02': 'Token do remetente não encontrado',
    'TK03': 'Token do destinatário não encontrado',
    'TK04': 'Token expirado',
    'TK05': 'Token encontrado com incompatibilidade de contraparte',
    'TK06': 'Token encontrado com violação da regra de limite de valor',
    'TK07': 'Token de uso único já usado',
    'TK08': 'Token suspenso',
    'TM01': 'Tempo de corte inválido',
    'TXNLMT01': 'Falha no limite agregado da transação',
    'UPAY': 'Pagamento indevido - O pagamento foi feito por outro canal de pagamento (para expiração do pedido de pagamento)',
    'WIAM': 'Valor incorreto com indenização',
    'WICT': 'Com cliente indenizado',
    'WIDP': 'Com duplicidade de indenização',
    'WIFD': 'Com fraude de indenização',
    'WIFT': 'Resposta final com indenização',
    'WITH': 'Com indenização técnica',
    'XT04': 'Liquidez insuficiente para processar a transação no sistema.',
    'XT06': 'Tempo de aceitação inválido, rejeitado pelo CSM para o banco originador ao exceder o período de tolerância para a data e hora de aceitação',
    'XT75': 'Status da transação original inválido, ação não necessária',
    'XT79': 'O agente devedor não está autorizado a enviar transações SCT Inst (pacs.008) e, consequentemente, a enviar solicitações de status de pagamento (pacs.028) e recalls (camt.056). Também não está autorizado a receber NRR e PRR.',
    'XT80': 'O agente credor não está autorizado a receber transações SCT Inst (pacs.008) e, consequentemente, a receber solicitações de status de pagamento (pacs.028) e recalls (camt.056). Também não está autorizado a enviar NRR e PRR. (O perfil de admissão "Apenas Devedor" atualmente não está implementado)',
    'XT81': 'Campo não permitido no serviço SCT Inst',
    'XT83': 'Participantes remetentes e/ou destinatários não configurados para uso de CUG/AOS',
    'XT87': 'Agente instrutor inconsistente',
    '1100': 'O pagamento não pôde ser processado neste momento devido a um erro inesperado, por favor, tente novamente mais tarde',
    '9909': 'Mensagem TCH - Mau funcionamento do sistema de switch central (RTP)',
    '9910': 'Mensagem TCH - Agente instruído desconectado',
    '9912': 'Mensagem TCH - Conexão do destinatário não está disponível',
    '9934': 'Mensagem TCH - Agente instrutor desconectado',
    '9946': 'Mensagem TCH - Agente instrutor suspenso',
    '9947': 'Mensagem TCH - Agente instruído suspenso',
    '9948': 'Mensagem TCH - Serviço de switch central (RTP) suspenso',
    '9952': 'Mensagem TCH - Incompatibilidade de mapeamento entre Versão 1 e 2',
    '9953': 'Mensagem TCH - Código "FULL" ausente (valor total da fatura)',
    '9954': 'Mensagem TCH - Instruções ausentes para código do agente credor no Zelle RFP',
    '9956': 'Mensagem TCH - Conta de financiamento do agente instrutor suspensa',
    '9957': 'Mensagem TCH - Conta de financiamento do agente instruído suspensa',
    '9964': 'Mensagem TCH - Identificação de participante inválida',
    // 13000 - Códigos de erro
    'NARR': `Valor recebido não é o valor acordado ou esperado
            Falha não categorizada
            BIC desconhecido na tabela de roteamento`
}
