const GatewayCodesEs = {
    // 10000 - Códigos de error
    'CH21': `El código de identificación del banco especificado en el mensaje tiene un formato incorrecto
            El identificador del banco es inválido o falta
            El código de sucursal es inválido o falta
            Desajuste entre el BIC del agente acreedor y el IBAN
            Ocurrió un error en %FIELD_NAME_1%
            La transacción no es única`,
    'RC02': `El código de identificación del banco especificado en el mensaje tiene un formato incorrecto
            El identificador del banco es inválido o falta
            El código de sucursal es inválido o falta
            Desajuste entre el BIC del agente acreedor y el IBAN
            Ocurrió un error en %FIELD_NAME_1%
            La transacción no es única`,
    'DT01': 'Ocurrió un error en %FIELD_NAME_1%',
    'AM14': 'Ocurrió un error en %FIELD_NAME_1%. El monto de la transacción excede los límites acordados entre el banco y el cliente.',
    'AM06': 'Ocurrió un error en %FIELD_NAME_1%',
    'CH16': `La información de remesa estructurada incluye caracteres alfanuméricos o más de 16 dígitos
            Ocurrió un error en %FIELD_NAME_1%
            Código de país inválido
            Código QR caducado
            Estado del código QR inactivo`,
    'BE15': 'Ocurrió un error en %FIELD_NAME_1%. ID del proxy no activo',
    'NARR': 'Ocurrió un error en %FIELD_NAME_1%',
    // 11000 - Códigos de error
    'AB01': 'Proceso de compensación abortado debido a tiempo de espera agotado',
    'AB02': 'Proceso de compensación abortado debido a un error fatal',
    'AB03': 'Liquidación abortada debido a tiempo de espera agotado',
    'AB05': 'Transacción detenida debido a tiempo de espera agotado en el agente acreedor',
    'AB06': 'Transacción detenida debido a tiempo de espera agotado en el agente instruido',
    'AB07': 'El agente del mensaje no está en línea',
    'AB08': 'El agente acreedor no está en línea',
    'AB09': 'Transacción detenida debido a error en el agente acreedor',
    'AB10': 'Proceso de compensación abortado debido a error en el PSP intermediario o CSM (el agente instruido).',
    'AC04': 'El número de cuenta especificado ha sido cerrado en los libros del banco',
    'AC05': 'Número de cuenta del deudor cerrado',
    'AC06': 'La cuenta especificada está bloqueada, prohibiendo la publicación de transacciones en ella',
    'AC07': 'Número de cuenta del acreedor cerrado',
    'AG01': 'Transacción prohibida en este tipo de cuenta (anteriormente Sin Acuerdo)',
    'AG02': 'El código de operación bancaria especificado en el mensaje no es válido para el receptor',
    'AG03': 'Tipo de transacción no soportada o autorizada en esta cuenta',
    'AG07': 'La cuenta del deudor no puede ser debitada por una razón genérica',
    'AG09': 'Pago original nunca recibido',
    'AG10': 'El agente del mensaje está suspendido del sistema de pago en tiempo real',
    'AG11': 'El PSP del beneficiario del mensaje está suspendido del sistema de pago en tiempo real',
    'AG12': 'Falló la validación de la pre-autorización',
    'AM03': 'El monto del mensaje especificado es una moneda no procesable fuera del acuerdo existente',
    'AM04': 'El monto de los fondos disponibles para cubrir el monto del mensaje especificado es insuficiente',
    'AM05': 'Duplicación',
    'AM20': 'El número de transacciones en el nivel de información de pago es inválido',
    'ARDT': 'Ya devuelto. Cancelación no aceptada ya que la transacción ya ha sido devuelta.',
    'BE01': 'La identificación del cliente final no es consistente con el número de cuenta asociado.',
    'BE06': 'El cliente final especificado no es conocido en el código de clasificación o banco nacional o ya no existe en los libros',
    'BE07': 'La especificación de la dirección del deudor, que se requiere para el pago, falta/no es correcta',
    'BE10': 'El código de país del deudor falta o es inválido',
    'BE11': 'El código de país del acreedor falta o es inválido',
    'BE12': 'El código de país de residencia falta o es inválido',
    'CH09': 'No se permiten cambios en el mandato',
    'CH11': 'El valor en el identificador del acreedor es incorrecto',
    'CNOR': 'El banco acreedor no está registrado bajo este BIC en el CSM',
    'CUST': 'Cancelación solicitada por el deudor',
    'DNOR': 'El banco deudor no está registrado bajo este BIC en el CSM',
    'DS02': 'Pedido Cancelado',
    'DS04': 'Pedido Rechazado',
    'DS09': 'La desencriptación del archivo no fue exitosa',
    'DS0B': 'Firma de datos para el formato no está disponible o es inválida',
    'DS0D': 'Certificado de firma no válido',
    'DS0G': 'El firmante no está autorizado para firmar este tipo de operación.',
    'DS0H': 'El firmante no está autorizado para firmar para esta cuenta',
    'DS24': 'Tiempo de espera expirado',
    'EC46': 'Rechazo por sanciones',
    'ED05': 'Falló la liquidación de la transacción',
    'ED06': 'Sistema de liquidación interbancaria no disponible',
    'FF01': 'Formato del archivo incompleto o inválido',
    'FF02': 'Error de sintaxis, razón proporcionada como información narrativa en la información adicional de motivo',
    'FF03': 'Información del tipo de pago falta o es inválida',
    'FF10': 'El archivo o la transacción no puede ser procesado debido a problemas técnicos en el lado del banco',
    'FF11': 'Solicitud de compensación rechazada por estar sujeta a una operación de abortamiento',
    'FOCR': 'Siguiendo solicitud de cancelación',
    'FR01': 'Devuelto como resultado de fraude',
    'FRAD': 'Transacción SCT Inst original fraudulenta',
    'FRAUD01': 'La cuenta del acreedor no es elegible para pagos en tiempo real. Su pago no pudo ser procesado.',
    'FRTR': 'Respuesta final - Reintento de intento previo sin respuesta.',
    'IN06': 'El ABA del acreedor no es elegible para pagos en tiempo real. Su pago no pudo ser procesado.',
    'IN12': 'El canal designado no es elegible para pagos en tiempo real. Su pago no pudo ser procesado.',
    'IN14': 'El pago tiene campos que exceden los límites de caracteres. Por favor, haga las correcciones necesarias y vuelva a intentarlo.',
    'LEGL': 'Decisión Legal',
    'MD01': 'Sin Mandato',
    'MD02': 'La información relacionada con el mandato requerida por el esquema falta',
    'MD06': 'Devolución de fondos solicitada por el cliente final',
    'MD07': 'Cliente final fallecido',
    'NOAS': 'Sin respuesta del Beneficiario',
    'NOAT': 'Mensaje TCH - La cuenta del cliente receptor no soporta/acepta este tipo de mensaje',
    'NOOR': 'Transacción SCT Inst inicial nunca recibida',
    'PC04': 'Tarjeta perdida/robada',
    'PC05': 'Rechazado',
    'PC43': 'Tarjeta perdida/robada',
    'PC57': 'Transacción no permitida para el titular de la tarjeta',
    'PC61': 'Excede los límites de retiro',
    'PC62': 'Tarjeta restringida',
    'PC65': 'Límite de conteo de actividades excedido',
    'PR05': 'Proxy duplicado en el banco',
    'PR06': 'Proxy duplicado en otro banco',
    'PR07': 'Proxy ya registrado/transferido',
    'PR08': 'Proxy ya desregistrado',
    'PR09': 'Proxy ya suspendido',
    'PR10': 'Tiempo de espera de la solicitud de proxy',
    'PR11': 'Otro motivo de rechazo del proxy',
    'RC09': 'Identificador del miembro del sistema de compensación del deudor es inválido o falta',
    'RC10': 'Identificador del miembro del sistema de compensación del acreedor es inválido o falta',
    'RF01': 'La referencia de la transacción no es única dentro del mensaje',
    'RR04': 'Motivo regulatorio',
    'RR05': 'Información de reporte regulatorio o del banco central falta, incompleta o inválida',
    'RR10': 'Conjunto de caracteres proporcionado no es válido para el país y tipo de pago.',
    'SL03': 'Debido a un servicio específico ofrecido por el sistema de compensación',
    'TA01': 'La transmisión del archivo no fue exitosa, tuvo que ser abortada (por razones técnicas)',
    'TECH': 'Problema Técnico',
    'TK01': 'Token inválido',
    'TK02': 'Token del remitente no encontrado',
    'TK03': 'Token del destinatario no encontrado',
    'TK04': 'Token expirado',
    'TK05': 'Token encontrado con incompatibilidad de contraparte',
    'TK06': 'Token encontrado con violación de la regla de límite de valor',
    'TK07': 'Token de uso único ya utilizado',
    'TK08': 'Token suspendido',
    'TM01': 'Tiempo límite inválido',
    'TXNLMT01': 'Fallo en el límite agregado de la transacción',
    'UPAY': 'Pago indebido - El pago se realizó a través de otro canal de pago (para la expiración de la solicitud de pago)',
    'WIAM': 'Cantidad incorrecta con indemnización',
    'WICT': 'Con cliente indemnizado',
    'WIDP': 'Con duplicación de indemnización',
    'WIFD': 'Con fraude de indemnización',
    'WIFT': 'Respuesta final con indemnización',
    'WITH': 'Con indemnización técnica',
    'XT04': 'Liquidez insuficiente para procesar la transacción en el sistema.',
    'XT06': 'Tiempo de aceptación inválido, rechazado por el CSM al banco originador al exceder el período de tolerancia para la fecha y hora de aceptación',
    'XT75': 'Estado original de la transacción inválido, acción no requerida',
    'XT79': 'El agente deudor no está autorizado a enviar transacciones SCT Inst (pacs.008) y, en consecuencia, a enviar solicitudes de estado de pago (pacs.028) y devoluciones (camt.056). Tampoco está autorizado a recibir NRR y PRR.',
    'XT80': 'El agente acreedor no está autorizado a recibir transacciones SCT Inst (pacs.008) y, en consecuencia, a recibir solicitudes de estado de pago (pacs.028) y devoluciones (camt.056). Tampoco está autorizado a enviar NRR y PRR. (El perfil de admisión "Solo Deudor" actualmente no está implementado)',
    'XT81': 'Campo no permitido en el servicio SCT Inst',
    'XT83': 'Participantes remitentes y/o receptores no configurados para uso de CUG/AOS',
    'XT87': 'Agente instructor inconsistente',
    '1100': 'El pago no pudo ser procesado en este momento debido a un error inesperado, por favor, intente nuevamente más tarde',
    '9909': 'Mensaje TCH - Mal funcionamiento del sistema de conmutación central (RTP)',
    '9910': 'Mensaje TCH - Agente instruido desconectado',
    '9912': 'Mensaje TCH - Conexión del destinatario no disponible',
    '9934': 'Mensaje TCH - Agente instructor desconectado',
    '9946': 'Mensaje TCH - Agente instructor suspendido',
    '9947': 'Mensaje TCH - Agente instruido suspendido',
    '9948': 'Mensaje TCH - Servicio de conmutación central (RTP) suspendido',
    '9952': 'Mensaje TCH - Incompatibilidad de mapeo entre la versión 1 y 2',
    '9953': 'Mensaje TCH - Código "FULL" ausente (monto total de la factura)',
    '9954': 'Mensaje TCH - Instrucciones ausentes para el código del agente acreedor en Zelle RFP',
    '9956': 'Mensaje TCH - Cuenta de financiamiento del agente instructor suspendida',
    '9957': 'Mensaje TCH - Cuenta de financiamiento del agente instruido suspendida',
    '9964': 'Mensaje TCH - Identificación del participante inválida',
    // 13000 - Códigos de error
    'NARR': `El monto recibido no es el monto acordado o esperado
            Fallo no categorizado
            BIC desconocido en la tabla de enrutamiento`
}
